# Generated by Django 5.2.6 on 2025-09-11 20:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]
    operations = [
        migrations.AlterModelOptions(
            name='ngoprofile',
            options={'verbose_name': 'NGO Profile', 'verbose_name_plural': 'NGO Profiles'},
        ),
        migrations.AlterModelOptions(
            name='restaurantprofile',
            options={'verbose_name': 'Restaurant Profile', 'verbose_name_plural': 'Restaurant Profiles'},
        ),
        migrations.AddField(
            model_name='ngoprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('ngo', 'NGO'), ('admin', 'Admin'), ('delivery_agent', 'Delivery Agent')], db_index=True, default='restaurant', max_length=32),
        ),
    ]
