# Generated by Django 5.2.6 on 2025-09-11 20:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('fulfilled', 'Fulfilled')], db_index=True, default='pending', max_length=32)),
                ('message', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='donationrequest',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='donationrequest',
            name='donation',
        ),
        migrations.RemoveField(
            model_name='donationrequest',
            name='ngo',
        ),
        migrations.AlterModelOptions(
            name='fooddonation',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='fooddonation',
            name='address',
        ),
        migrations.RemoveField(
            model_name='fooddonation',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='fooddonation',
            name='prepared_at',
        ),
        migrations.RemoveField(
            model_name='fooddonation',
            name='title',
        ),
        migrations.AddField(
            model_name='fooddonation',
            name='expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fooddonation',
            name='food_type',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='fooddonation',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fooddonation',
            name='pickup_address',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='fooddonation',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='fooddonation',
            name='restaurant',
            field=models.ForeignKey(limit_choices_to={'role': 'restaurant'}, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fooddonation',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('collected', 'Collected'), ('distributed', 'Distributed'), ('cancelled', 'Cancelled')], db_index=True, default='available', max_length=32),
        ),
        migrations.AddIndex(
            model_name='fooddonation',
            index=models.Index(fields=['status'], name='donations_f_status_4c3735_idx'),
        ),
        migrations.AddIndex(
            model_name='fooddonation',
            index=models.Index(fields=['expiry'], name='donations_f_expiry_431418_idx'),
        ),
        migrations.AddField(
            model_name='request',
            name='donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='donations.fooddonation'),
        ),
        migrations.AddField(
            model_name='request',
            name='ngo',
            field=models.ForeignKey(limit_choices_to={'role': 'ngo'}, on_delete=django.db.models.deletion.CASCADE, related_name='requests_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DonationRequest',
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['status'], name='donations_r_status_2a3a14_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='request',
            unique_together={('donation', 'ngo')},
        ),
    ]
