# Generated by Django 5.2.6 on 2025-09-11 20:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
        ('donations', '0002_request_alter_donationrequest_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='assigned_agent',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='current_latitude',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='current_longitude',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='donation',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='ngo',
        ),
        migrations.AddField(
            model_name='delivery',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_agent',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'delivery_agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delivery',
            name='location_updates',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='delivery',
            name='quality_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('good', 'Good'), ('spoiled', 'Spoiled')], default='unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='delivery',
            name='request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='donations.request'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('failed', 'Failed')], db_index=True, default='assigned', max_length=32),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['status'], name='deliveries__status_bdfe1b_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['updated_at'], name='deliveries__updated_03d7b0_idx'),
        ),
    ]
